packages:
  - 'example'
  - 'packages/*'
catalog:
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "@vitest/coverage-v8": "3.0.7"
  vitest: '3.0.7'
  typescript: '5.8.2'
  eslint: '9.14.0'
  react: '19.0.0'
  'react-dom': '19.0.0'
