packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  "@types/react": "^19.1.2"
  "@types/react-dom": "^19.1.2"
  "@vitest/coverage-v8": "3.1.1"
  vitest: '3.1.1'
  typescript: '5.8.2'
  react: '19.1.0'
  'react-dom': '19.1.0'
