packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.5
  '@vitest/coverage-v8': ^3.2.4
  vitest: ^3.2.4
  typescript: 5.8.2
  react: 19.1.0
  react-dom: 19.1.0
