packages:
  - 'example'
  - 'packages/*'
catalog:
  '@types/react': 18.3.3
  '@types/react-dom': 18.3.0
  vitest: '2.1.9'
  typescript: '5.6.3'
  eslint: '9.14.0'
  react: '18.3.1'
  'react-dom': '18.3.1'
